export const SET_LOAN_FETCH_LOADING = 'SET_LOAN_FETCH_LOADING';
export const LOAN_FETCH_DETAILS_SUCCESS = 'LOAN_FETCH_DETAILS_SUCCESS';

export const SET_LOAN_ACTION_LOADING = 'SET_LOAN_ACTION_LOADING';
export const LOAN_ACTION_SUCCESS = 'LOAN_ACTION_SUCCESS';
export const SET_LOAN_ACTION_ERROR = 'SET_LOAN_ACTION_ERROR';
