export const SET_LOAN_FETCH_LOADING = 'SET_LOAN_FETCH_LOADING';
export const SET_LOAN_FETCH_DETAILS = 'SET_LOAN_FETCH_DETAILS';

export const SET_LOAN_ACTION_LOADING = 'SET_LOAN_ACTION_LOADING';
export const SET_LOAN_ACTION = 'SET_LOAN_ACTION';
export const SET_LOAN_ACTION_ERROR = 'SET_LOAN_ACTION_ERROR';
