#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 CERN.
#
# invenio-app-ils is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

# You can pass the --beat argument if you want the beat to run
celery -A invenio_app.celery worker -l INFO & pid_celery=$!
