#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2018-2023 CERN.
# SPDX-License-Identifier: MIT

set -e

script_path=$(dirname "$0")
FLASK_ENV=development invenio run \
    --cert "$script_path"/../docker/frontend/test.crt \
    --key "$script_path"/../docker/frontend/test.key
