#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 CERN.
#
# invenio-app-ils is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

set -e

# Clean redis
ils shell --no-term-title -c "import redis; redis.StrictRedis.from_url(app.config['CACHE_REDIS_URL']).flushall(); print('Cache cleared')"
ils db destroy --yes-i-know
ils db init create
ils index destroy --force --yes-i-know
ils index init --force
ils index queue init purge

# Create roles to rectict access
ils roles create admin
ils roles create librarian

# create users
ils users create admin@test.ch -a --password=123456
ils users create librarian@test.ch -a --password=123456
ils users create patron@test.ch -a --password=123456

ils roles add admin@test.ch admin
ils roles add librarian@test.ch librarian
ils access allow superuser-access role admin
ils access allow ils-librarian-access role librarian
